name = "mindfit"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_APP_NAME = "Mindfit"
NEXT_PUBLIC_APP_URL = "https://mindfit.pages.dev"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "mindfit-d14f7"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "mindfit-d14f7.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "mindfit-d14f7.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "133329052719"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:133329052719:web:b54af460b83255563712da"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-6TJFCRLX1N"
